workflows:
  expo-bare-build:
    name: Build Android & iOS (Expo Prebuild)
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      node: stable
      cocoapods: default
      ruby: default
      xcode: latest
      android:
        build_tools: "31.0.0"
        ndk: "21.4.7075529"

      android_signing:
        - keystore_ref_name

      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.spinkdev.x47propcalc

    scripts:
      - name: Clear Cache before install
        script: |
          rm -rf node_modules
          npm cache clean --force

      - name: Install Dependencies
        script: |
          npm ci

      - name: Expo Prebuild
        script: |
          npx expo prebuild --non-interactive --clean

      - name: CocoaPods Install
        script: |
          npx pod-install ios

      - name: Build Android (AAB)
        script: |
          cd android
          ./gradlew bundleRelease
          cd ..

      - name: Build iOS IPA
        script: |
          xcode-project build-ipa \
            --workspace ios/x47PropCalc.xcworkspace \
            --scheme x47PropCalc \
            --export-method app-store

    artifacts:
      - android/app/build/outputs/bundle/release/*.aab
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - x47base@proton.me
