workflows:
  default-workflow:
    name: x47PropCalc-build
    environment:
      vars:
        EXPO_PROJECT_ID: "4cd4c5c0-64b2-43c8-a961-c08dd48bc054"
        APP_SCHEME: "com.spinkdev.x47propcalc"
        APP_PACKAGE: "com.spinkdev.x47propcalc"
      node: latest
      expo: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install --force
      - name: Build Android APK
        script: |
          eas build --platform android --non-interactive --profile development
      - name: Build iOS IPA
        script: |
          eas build --platform ios --non-interactive --profile development
    artifacts:
      - build/android/*.apk
      - build/ios/*.ipa
    publishing:
      email:
        recipients:
          - x47base@proton.me
        notify:
          success: true
          failure: true